joueurs: []

soigner: []

musique: []

motsTrad:
- Montrer:Achilika
- Pouvoir:Agh
- Adieu:Aglou
- Beaucoup:Agol
- Nombreux:Agol
- Plusieurs:Agol
- Vouloir:Akala
- Dépécher:Akiita
- Donner:Aknouh
- Arrêter:Algo
- Stop:Algo
- Mentir:Amzo
- Ta:Ati
- Tes:Ati
- Toi:Ati
- Aurevoir:Atoonza
- Niveau:Atoulka
- Passer:Azerofh
- Ralentir:Azodo
- Prendre:Beula
- Vous:Bladola
- Non:Blok
- Sandwich:Bok
- Porte:Borka
- Boule:Boulik
- Bourrin:Bourrino
- Foncer:Bourrino
- Marcher:Bozoh
- Épée:Bragoul
- Arme:Bragoul
- Loin:Broudaf
- Lointain:Broudaf
- Arracher:Broum
- Mètre:Chokma
- Route:Clog
- Pratique:Crao
- Léviter:Cuicui
- Oiseau:Cuicui
- Voler:Cuicui
- Piège:Da
- Pas:Dak
- Vieille:Dalouk
- Vieux:Dalouk
- Vaincre:Dam
- Plus:Dar
- Fêter:Djinlgebelh
- Nous:Dkajo
- Attraper:Dlakou
- Dormir:Dodo
- Sommeil:Dodo
- Porte:Doordo
- Nain:Dorva
- Merci:Doula
- Comestible:Doulo
- Dur:Doumva
- Dragon:Dragoulou
- Gros:Droula
- Attaquer:Drulugah
- Chose:Dzo
- Balancer:Dzoubala
- Lancer:Dzoubala
- Kalounga:Entendre
- Devoir:Eto
- Donc:Eto
- Tenir:Etso
- Sortir:Exta
- Humain:Faloukou
- Pour:Forlaa
- Écraser:Frakass
- Défoncer:Frakass
- Fracasser:Frakass
- Enfoncer:Galoun
- Appuyer:Gasna
- Froid:Glagla
- Orque:Glakou
- Méchant:Glakoul
- Mal:Glakoul
- Mauvais:Glakoul
- Acheter:Glikido
- Super:Glok
- Tête:Glok
- Finir:Glorkou
- Terminer:Gloubok
- Excuser:Gloudouk
- Pardon:Gloudouk
- Pardonner:Gloudouk
- Boire:Glouglou
- Blaguer:Gluku
- Déconner:Gluku
- Voir:Gnagof
- Amazone:Gnagola
- Barbare:Gnagolo
- Emmerder:Gnolo
- Gobelin:Gobbo
- Chance:Gof
- Grillade:Gol
- Aimer:Gola
- Pareil:Golo
- Voilà:Golo
- Cochon:Gorki
- Porc:Gorki
- Bonjour:Gotfeurdom
- Approcher:Goulada
- Attention:Goulak
- Repérer:Goz
- Casser:Grao
- Guitare:Gratgrat
- Pourquoi:Gravoz
- Garder:Grok
- Toujours:Groubouf
- Grand:Grouf
- Porter:Gruh
- Transporter:Gruh
- Couper:Grunt
- Découper:Grunt
- Filer:Hatlouk
- Partir:Hatlouk
- Maison:Hol
- Chuter:Hopla
- Tomber:Hopla
- Dans:Houla
- Dedans:Houla
- Intérieur:Houla
- Éprouver:Hounk
- Répéter:Huk
- Entrer:Inta
- Expérience:Ixpe
- Amuser:Jolzio
- Pour:Kadoula
- Ombre:Kagoula
- Vite:Kal kal
- Entendre:Kalounga
- Trouver:Kligudu
- Ami:Kopain
- Féliciter:Koulaga
- Ailleurs:Louk
- Habit:Ma
- Vêtement:Ma
- Poubelle:Makkd'oh
- Saleté:Makkd'oh
- Manger:Miam
- Frapper:Mourk
- Nanana:Nanana
- Perdu:Noal
- Bonne nuit:Dlabou
- Charogne:Oklagh
- Etage:Ol
- Anesthésier:Opog
- Endormir:Opog
- Orc:Orkoum
- Graisse:Palaf
- Gras:Palaf
- Ne:pas
- Vraiment:plaf
- Très:plaf
- Armure:Plaktu
- Caca:Popoh
- Merde:Popoh
- Saucisse:Pouk
- Génie:Razogh
- Bandit:Rbindeboi
- De rien:Schlobok
- Table:Rova
- Gemme:Sakoul
- Minerais:Sakoul
- Exact:Shlova
- Bon:Slouba
- Bonne:Slouba
- Éclabousser:Splach
- Eau:Splach
- Flaque:Splach
- Besoin:Splati
- Aplatir:Splonrch
- Écrabouiller:Sprotch
- Tuer:Sprotch
- Quoi:Swobok
- Balancer:Taak
- Jeter:Taak
- Offrir:Tablok
- Taille:Tadla
- Gratter:Tagala
- Petit:Tagoula
- Mage:Taka
- Magicien:Taka
- Sorcier:Taka
- Amadouer:Tako
- Charmer:Tako
- Dresser:Tako
- Moquer:Talof
- Bras:Talok
- Peau-verte:Tchok
- Crever:Tlakoh
- Tous:Toka
- Demander:Toko
- Comprendre:Tol
- Coucher:Toudlag
- Troll:Toukala
- Troll:Toukalo
- Idiot:Toulos
- Stupide:Toulos
- Chanson:Tounda
- Savoir:Turlu
- Ici:Ugluduk
- Cheveux:Veuk
- Cacher:Vo
- Chier:Volo
- Chanter:Vrotapa
- Jambon:Yabo
- Lait:Yagourt
- Puer:Zaboufka
- Posséder:Zadoum
- Monstre:Zaloss
- Avec:Zamok
- Avancer:Zatal
- Flèche:Zavol
- Cave:Znivo
- Caveau:Znivo
- Dessous:Znivo
- Sous-sol:Znivo
- Pied:Zod
- Près:Zof
- Proche:Zof
- Démon:Zog
- Oui:Zog zog
- Finir:Zogdo
- Ouais:Zogla
- Mourir:Zom
- Passage:Zomva
- Passer:Zomva
- Venir:Zomva
- Odeur:Zoub
- Sentir:Zoub
- Auberge:Zoubla
- Tanière:Zoubla
- Faire:Zoul
- Attendre:Zoulag
- Patienter:Zoulag
- Bizarre:Zpotla
- Caillou:Zulu
- Pierre:Zulu
- Roche:Zulu
- Aller:Zyva
